trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: dolittle-tools/Build
      endpoint: dolittle-tools

jobs:
- template: dotnet.yml@templates
  parameters:
    CASCADES: 6a011156-dec2-44a1-b4f6-718ddc28c413 a5f5239e-c774-4933-ae09-6573de30e5ef